seed:
    42
data_split:
    0.1

dataloader:
    "batch_size": 64
    "num_workers": 2
    "persistent_workers": True
    #"pin_memory": False
    #"prefetch_factor": None

model:
    "feature_dim": 21
    "embed_dim": 128
    "num_heads": 8
    "dropout": 0.1
    "mlp_ratio": 4
    "eval_hidden_dim": 128
    "num_layers": 12 # 8-12
    "n_recycles": 4

loss:
    'eval_loss_weight': 0.5
    'move_loss_weight': 1
    'threat_loss_weight': 0.2
    'incheck_loss_weight': 0.1
    'use_move_weight': False # weight moves differently depending on whether they led to win/loss/draw

train:
    'lr': 0.0001
    'weight_decay': 0.01
    'T_max': 2
    'max_epochs': 2
    #'device': 'mps'