name: chess_engine
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-lightning
  - matplotlib
  - pytest
  - pyyaml
  - python-dotenv
  - pip
  - pip:
      - chess
      - torch-scatter